import { createSlice } from "@reduxjs/toolkit";

const mongoDBSlice = createSlice({
  name: 'mongodb',
  initialState: {
     buildingData: [],
     defBuildingInfo: [
      {
        id: 1,
        title: 'IT Building and Library' ,
        description: 'Thsi Building has 2 floors',
        latitude:  9.353699 ,
        longitude: 122.836321,
        latitudeText:  9.353699 ,
        longitudeText: 122.836321 ,
        textInfo: 'IT Building and Library',
        uri: 9 ,
        buildingData: {
          numberOfFloors: 2,
          numberOfRooms: 8,
          groundFloorNumRooms: 0,
          groundRoom: [],
          groundFloorNumRooms: 0,
          groundRoom: ['Multimedia', 'IT Office', 'Faculty Room', 'Stock Room', 'IT101', 'IT102', 'IT103'],
          firstFloorNumRooms: 7,
          firstRoom: ['Library'],
          secondFloorNumRooms: 1,
          secondRoom: [],
          thirdFloorRooms: 0,
          thirdRoom: [],
          fourthFloorNumRooms: 0,
          fourthRoom: []
       }
     },
     {
        id: 2,
       title: "AMPHITHEATER " ,
       description: " This AMPHITHEATER  Area" ,
       latitude:  9.353286 ,
       longitude: 122.838275 ,
       latitudeText: 9.353288, 
       longitudeText: 122.838313 ,
       textInfo: 'AMPHITHEATER ' ,
       uri: 30,
       buildingData: {
         numberOfFloors: 1,
         numberOfRooms: 7,
         noRooms: true,
         noRoomsText: 'This Outdoor space is dedicated for performances/events',
         groundFloorNumRooms: 0,
         groundRoom: [],
         firstFloorNumRooms: 7,
         firstRoom: ['Multimedia', 'IT Office', 'Faculty Room', 'Stock Room', 'IT101', 'IT102', 'IT103'],
         secondFloorNumRooms: 0,
         secondRoom: [],
         thirdFloorRooms: 0,
         thirdRoom: [],
         fourthFloorNumRooms: 0,
         fourthRoom: []
       }
    },
    {
      id: 3,
     title: 'CBA Building' ,
   description: 'CBA consist of 2 floors' ,
     textInfo: 'CBA Building' ,
     uri: 11,  
     latitude: 9.353911  ,
     longitude: 122.836058,
     latitudeText: 9.353930,
     longitudeText:  122.836070,
     buildingData: {
      numberOfFloors: 3 ,
      numberOfRooms:  6,
      groundFloorNumRooms: 2,
      groundRoom: ['Faculty Room' ,'CBA 1'],
      firstFloorNumRooms: 2,
      firstRoom: ['Faculty Room ','CBA 2' ],
      secondFloorNumRooms: 2,
      secondRoom: ['CBA 3', 'CBA SG Office' ],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
    {
      id: 4,
     title: 'Electrical Power Center Building',
     description: 'Norsu Generator' ,
     textInfo: 'Electrical Power Center',
     uri: 12,
     latitude: 9.352890 ,
     longitude:  122.836552,
     latitudeText: 9.352916,
     longitudeText: 122.836568 ,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 1,
      noRooms: true,
      noRoomsText: "This is electrical power is being managed. Reminder: Students are not allowed to enter this building without permission for safety reasons. ",
      groundFloorNumRooms: 0,
      groundRoom: [],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
   {
      id: 5,
     title: 'Norsu Canteen',
     description: 'Norsu Public Canteen' ,
     textInfo: 'Norsu Canteen ' ,
     uri:7 ,
     latitude:  9.353078 ,
     longitude: 122.837478 ,
     latitudeText:  9.353112,
     longitudeText: 122.837485 ,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 1,
      noRooms: true,
      noRoomsText: 'Provides food service for students and staff of NORSU-BSC',
      groundFloorNumRooms: 0,
      groundRoom: [],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
   {
      id: 6,
    title: "AVR Building" ,
    description: "This is the AVR Building" ,
    textInfo: 'AVR',
     uri:  1,
     latitude: 9.353657 ,
     longitude: 122.836621 ,
     latitudeText: 9.353657  ,
     longitudeText:  122.836621 ,
     buildingData: {
         numberOfFloors: 1,
         numberOfRooms: 1,
         noRooms:true,
         noRoomsText: 'This is the Audio Visual Room  ',
         groundFloorNumRooms: 0,
         groundRoom: [],
         firstFloorNumRooms: 0,
         firstRoom: [],
         secondFloorNumRooms: 0,
         secondRoom: [],
         thirdFloorRooms: 0,
         thirdRoom: [],
         fourthFloorNumRooms: 0,
         fourthRoom: []
   }
   },
   {
     id: 7,
      title: "Building 1",
     description: "This is the Registrar/Accounting Building" ,
     textInfo: 'Registrar/Accounting Building' ,
     uri: 13 ,
     latitude: 9.352464 ,
     longitude: 122.837693,
     latitudeText: 9.352501 ,
     longitudeText: 122.837704 ,
     buildingData: {
      numberOfFloors: 2,
      numberOfRooms: 4,
      groundFloorNumRooms: 4,
      groundRoom: ['University Security Management Office (USMO)' , 'Registrar', 'Accounting Office', 'Cashier'],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
   {
     id: 8,
       title: "Campus Clinic  " ,
     description: "This is the Campus Clinic Building " ,
     textInfo: 'Campus Clinic ' ,
     uri: 15,
     latitude: 9.352737 ,
     longitude: 122.838241,
     latitudeText: 9.352750 ,
     longitudeText: 122.838220,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 1,
      noRooms: true,
      noRoomsText: 'This Building provides Provides Healthcare for students and staff of NORSU-BSC',
      groundFloorNumRooms: 0,
      groundRoom: [],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
   {
     id: 9,
     title: "Accreditation Room" ,
     description: "Accreditation Room" ,
     textInfo: 'Accreditation Room' ,
     uri:  3,
     latitude: 9.352678 ,
     longitude: 122.838348 ,
     latitudeText:  9.352705 ,
     longitudeText:  482.838361,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 1,
      groundFloorNumRooms: 0,
      groundRoom: [],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
   {
     id: 10,
      title: "Office of the University President" ,
     description: "Office of the University President",
     textInfo: 'University President ' ,
     uri:  18 ,
     latitude: 9.352620,
     longitude: 122.838510 ,
     latitudeText: 9.352570 ,
     longitudeText: 122.838510,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 1,
      groundFloorNumRooms: 0,
      groundRoom: [],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
   {
     id: 11,
     title:  "Research and Extension Office",
     description: "Research and Extension Office" ,
     textInfo: 'Research and Extension Office' ,
     uri:  22,
     latitude: 9.352676 ,
     longitude:  122.838545,
     latitudeText: 9.352687 ,
     longitudeText: 482.838538 ,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 1,
      groundFloorNumRooms: 0,
      groundRoom: [],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
   {
    id: 12,
     title: "SSG Office" ,
     description: "SG Office" ,
     textInfo: 'SSG Office' ,
     uri: 19 ,
     latitude: 9.352649,
     longitude: 122.838716 ,
     latitudeText: 9.352657, 
     longitudeText: 122.838715,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 1,
      noRooms: true,
      noRoomsText: 'This Building is for the Office for SSG Officers',
      groundFloorNumRooms: 0,
      groundRoom: [],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
   {
    id: 13,
     title: "HR",
     description: "HR" ,
     textInfo:"HR" ,
     uri: 21,
     latitude: 9.352637 ,
     longitude: 122.838823 ,
     latitudeText: 9.352651 ,
     longitudeText: 122.838835 ,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 1,
      noRooms: true,
      noRoomsText: 'This Building is Human Resources Office',
      groundFloorNumRooms: 0,
      groundRoom: [],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
     
   {
    id: 14,
    title: " Student Center ",
     description: " Student Center ",
     textInfo: " Student Center " ,
     uri:38 ,
     latitude: 9.352583, 
     longitude: 122.838990 ,
     latitudeText: 9.352601, 
     longitudeText: 122.838990,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 1,
      noRooms: true,
      noRoomsText: ' This Area is the Central Hub for Student Activities',
      groundFloorNumRooms: 0,
      groundRoom: [],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
     
   {
    id: 15,
    title: " CAS Building " ,
     description: " This is the CAS Building" ,
     textInfo: 'CAS Building ' ,
     uri: 29 ,
     latitude: 9.352981  ,
     longitude: 122.838826  ,
     latitudeText: 9.352931 ,
     longitudeText: 122.838826,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 6,
      groundFloorNumRooms: 6,
      groundRoom: ['CAS Faculty',' CAS 13','CAS 14','CAS 15' ,'CAS 16' ,'CAS 17'],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
     
   {
    id: 16,
      title: " CAF Building  " ,
     description:  " CAF Building ",
     textInfo: " CAF Building " ,
     uri: 14,
     latitude:  9.352825 ,
     longitude:  122.837980 ,
     latitudeText: 9.352865  ,
     longitudeText: 482.837937 ,
     buildingData: {
      numberOfFloors: 2,
      numberOfRooms: 9,
      groundFloorNumRooms: 5,
      groundRoom: ['CAF 1', 'CAF 2', 'Faculty Room', 'Faculty Room', 'CAF SG Office'],
      firstFloorNumRooms: 4,
      firstRoom: ['Animal Science Laboratory', 'CAF 6', 'CAF 7| Crop Science Laboratory', ' CAF 8 | Crop Protection Laboratory' ],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
     
   {
    id: 17,
     title: "CCJE SG Office",
     description: " This is the CCJE SG Office ",
     textInfo: " CCJE SG Office" ,
     uri: 20,
     latitude: 9.352691, 
     longitude: 122.838739 ,
     latitudeText: 9.352711  ,
     longitudeText:  122.838743,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 1,
      groundFloorNumRooms: 0,
      groundRoom: [],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },

   {
    id: 18,
     title: " Building 2 ",
     description: " Building 2" ,
     textInfo: " Building 2" ,
     uri: 17,
     latitude:  9.352251 ,
     longitude: 122.838355 ,
     latitudeText:  9.352267,  
     longitudeText: 122.838360,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 1,
      groundFloorNumRooms: 0,
      groundRoom: [],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
     
   {
    id: 19,
     title: " Alumni Office" ,
     description: " This is the Alumni Office " ,
     textInfo: " Alumni Office ",
     uri: 17,
     latitude: 9.352324  ,
     longitude: 122.838399 ,
     latitudeText: 9.352334 ,
     longitudeText:  482.838409 ,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 1,
      noRooms: true,
      noRoomsText: 'This Building is an Office Room',
      groundFloorNumRooms: 0,
      groundRoom: [],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   }, 
   {
    id: 20,
     title: "Classroom Building 1" ,
     description: " 2 Rooms CBA/CED" ,
     textInfo: 'Classroom Building 1',
     uri: 25 ,
     latitude: 9.353185 ,
     longitude: 122.837797  ,
     latitudeText: 9.353192  ,
     longitudeText: 122.837797 ,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 2,
      groundFloorNumRooms: 2,
      groundRoom: ['CED 6/ CBA 5', 'CED 7/ CBA 5'],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
   {
    id: 21,
     title:"Classroom Building 2",
     description: " CED8 && CED9" ,
     textInfo: "Classroom Building 2",
     uri: 26 ,
     latitude: 9.353100  ,
     longitude:  122.837971  ,
     latitudeText:  9.353127   ,
     longitudeText: 122.837971  ,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 2,
      groundFloorNumRooms: 2,
      groundRoom: ['CED 08', 'CED 09'],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
     
   {
      id: 22,
      title: "Classroom Building 3" ,
     description: " Ass. Campus Admin, CED10, 2 No Label Rooms" ,
     textInfo: 'Classroom Building 3',
     uri: 27,
     latitude: 9.353025 ,
     longitude:  122.838187 ,
     latitudeText: 9.353042  ,
     longitudeText:122.838187  ,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 4,
      groundFloorNumRooms: 4,
      groundRoom: ['Office of the Campus Administrator', 'CED 10', 'Room', 'Room'],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
   {
    id: 23,
     title: "Accreditation Room (PHASE 2)" ,
     description: "Accreditation Room (PHASE 2)" ,
     textInfo: "Accreditation Room (PHASE 2)" ,
     uri: 4, 
     latitude: 9.352881 ,
     longitude: 122.838551  ,
     latitudeText: 9.352881   ,
     longitudeText:122.838551  ,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 1,
      noRooms: true,
      noRoomsText: 'This building is Underconstruction',
      groundFloorNumRooms: 0,
      groundRoom: [],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
   {
    id: 24,
     title: "CAS SG Office" ,
     description: "CAS SG Office" ,
     textInfo: "CAS SG Office" ,
     uri: 24 , 
     latitude: 9.352856  ,
     longitude:  122.838620 ,
     latitudeText: 9.352870 ,
     longitudeText:  122.838620 ,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 1,
      noRooms: true,
      noRoomsText: 'This building Office for CAS SG Officers',
      groundFloorNumRooms: 0,
      groundRoom: [],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
     
   {
    id: 25,
     title: "ClassRoom Building 5" ,
     description: "ClassRoom Building 5" ,
     textInfo: "ClassRoom Building 5" ,
     uri: 23, 
     latitude: 9.352780  ,
     longitude: 122.838560  ,
     latitudeText:  9.352772  ,
     longitudeText: 482.838570 ,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 1,
      noRooms: true,
      noRoomsText: 'This is a ClassRoom Building',
      groundFloorNumRooms: 0,
      groundRoom: [],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
     
   {
    id: 26,
    title: "CARE CENTER " ,
     description: "CARE CENTER " ,
     textInfo: "CARE CENTER " ,
     uri: 32 , 
     latitude: 9.353339, 
     longitude:  122.838019,
     latitudeText: 9.353359, 
     longitudeText: 122.838015,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 1,
      noRooms: true,
      noRoomsText: 'This Building Provides counseling for students',
      groundFloorNumRooms: 0,
      groundRoom: [],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
     
   {
    id: 27,
     title: "SAS Building",
     description: "SAS Building" ,
     textInfo: "SAS Building" ,
     uri: 33, 
     latitude: 9.353431, 
     longitude: 122.838063 ,
     latitudeText: 9.353445, 
     longitudeText: 122.838063 ,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 1,
      noRooms: true,
      noRoomsText: 'This Building Provides services for student welfare',
      groundFloorNumRooms: 0,
      groundRoom: [],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
     
   {
    id: 28,
     title: "OFFICE OF THE CAMPUS ADMINISTRATOR" ,
     description: "OFFICE OF THE CAMPUS ADMINISTRATOR" ,
     textInfo: "OFFICE OF THE CAMPUS ADMINISTRATOR" ,
     uri: 31, 
     latitude:  9.353340 ,
     longitude: 122.838154  ,
     latitudeText: 9.353343,
     longitudeText:  122.838177 ,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 1,
      groundFloorNumRooms: 0,
      groundRoom: [],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
     
   {
    id: 29,
     title: "CCJE Faculty Building" ,
     description: "CCJE Building",
     textInfo: "CCJE Faculty Building" ,
     uri: 35 , 
     latitude:  9.353688, 
     longitude:  122.838059,
     latitudeText: 9.353708,
     longitudeText:  122.838056,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 1,
      noRooms: true,
      noRoomsText: 'This is the Faculty Office of Criminal Justice Education',
      groundFloorNumRooms: 0,
      groundRoom: [],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
     
   {
     id: 30,
     title: " Supply and Property Management Office" ,
     description: "This is the stock room" ,
     textInfo: 'Supply and Property Management Office',
     uri: 36, 
     latitude:  9.353455  ,
     longitude: 122.838661 ,
     latitudeText: 9.353478 ,
     longitudeText: 482.838640 ,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 1,
      noRooms: true,
      noRoomsText: 'This Building Manages school assets and supplies',
      groundFloorNumRooms: 0,
      groundRoom: [],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
     
   {
    id: 31,
    title: " CIT Building" ,
     description: "This is the CIT Building" ,
     textInfo: 'CIT Building',
     uri:40, 
     latitude: 9.353131,
     longitude:  122.839262 ,
     latitudeText: 9.353154, 
     longitudeText: 122.839242,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 5,
      groundFloorNumRooms: 5,
      groundRoom: ['CIT Faculty', 'Computer Technology', 'CIT 02', 'Office', 'Automotive Technology'],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
     
   {
     id: 32,
     title: "CIT Building 2" ,
     description: "This is the Automotive Labs",
     textInfo: 'CIT Buiding 2',
     uri: 41 ,
     latitude: 9.352890,  
     longitude: 122.839444  ,
     latitudeText: 9.352905, 
     longitudeText: 122.839443,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 4,
      groundFloorNumRooms: 4,
      groundRoom: ['CIT Laboratory (Automotive)' ,'Room', 'Room', 'Room',],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
   {
     id: 33,
     title: "CAS Building 2" ,
     description: "This building consist of CAS Rooms",
     textInfo: 'CAS Building 2' ,
     uri: 42 ,
     latitude:  9.353109, 
     longitude:  122.839808,
     latitudeText: 9.353130, 
     longitudeText: 122.839806,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms:  8,
      groundFloorNumRooms: 5,
      groundRoom: ['CAS 01', 'CAS 02', 'CAS 02', 'CAS 03', 'CAS 04', 'CAS 05', 'CAS 06', 'CAS 07', 'CAS 08',],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
   {
     id: 34,
     title: " Accademic Building " ,
     description: "This building is the Academic Building" ,
     textInfo: 'Academic Building',
     uri: 37 ,
     latitude: 9.354132  ,
     longitude: 122.837868 ,
     latitudeText:  9.354093 ,
     longitudeText: 482.837885 ,
     buildingData: {
      numberOfFloors: 2,
      numberOfRooms: 8,
      groundFloorNumRooms: 4,
      groundRoom: ['Wet Laboratory | Chemistry Room', 'Dry Laboratory | Chemistry Room', 'Biology | Laboratory Room', 'Office of the Campus Research Director'],
      firstFloorNumRooms: 4,
      firstRoom: ['CBA 4', 'Edutech Room', 'Crime | Laboratory Room', 'Moot Court'],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
   {
     id: 35,
     title:  " CCJE and CIT Room ",
     description: "This building is for the CCJE and CIT Department",
     textInfo: 'CCJE and CIT Building' ,
     uri:'39',
     latitude: 9.353710 ,
     longitude: 482.838740 ,
     latitudeText: 9.353740  ,
     longitudeText:  482.838740 ,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 8,
      groundFloorNumRooms: 8,
      groundRoom: ['CIT 07 | Electrical Technology', 'CIT 06 | Electrical Technology', 'Stock Room', 'CIT 05 | Electrical Technology', 'CCJE 03', 'CIT SG Office', 'CCJE 02', 'CCJE 01'],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: [] 
   }
   },
   {
     id: 36,
     title: "Ball Field",
     description: "This is the Ball Field Area" ,
     textInfo: ' Ball Field Area',
     uri: 'AVR',
     latitude:  9.354088, 
     longitude: 122.838941 ,
     latitudeText: 9.354117, 
     longitudeText: 122.838943,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 1,
      groundFloorNumRooms: 0,
      groundRoom: [],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
   {
     id: 37,
     title:  " Nursery Area",
     description: "This is the Nursery Area",
     textInfo: 'Nursery Area'   ,
     uri: 10 ,
     latitude:9.353281, 
     longitude: 122.836191 ,
     latitudeText: 9.353300 ,
     longitudeText: 482.836200,
     buildingData: {
      numberOfFloors: 1,
      numberOfRooms: 1,
      noRooms: true,
      noRoomsText: 'This Area is for plant cultivation',
      groundFloorNumRooms: 0,
      groundRoom: [],
      firstFloorNumRooms: 0,
      firstRoom: [],
      secondFloorNumRooms: 0,
      secondRoom: [],
      thirdFloorRooms: 0,
      thirdRoom: [],
      fourthFloorNumRooms: 0,
      fourthRoom: []
   }
   },
   {
      id: 38,
      title:  " College Of Teacher Education",
      description: "This is the CTED Building",
      textInfo: 'CTED Building'   ,
      uri: 34 ,
      latitude: 9.353465  ,
      longitude: 122.837607 ,
      latitudeText: 9.353479  ,
      longitudeText: 122.837607  ,
      buildingData: {
         numberOfFloors: 1,
         numberOfRooms: 7,
         groundFloorNumRooms: 7,
         groundRoom: ['Faculty Room', 'CED 01', 'CED 02', 'CED 03', 'CED 04', 'CTED SG Office', 'Room'],
         firstFloorNumRooms: 0,
         firstRoom: [],
         secondFloorNumRooms: 0,
         secondRoom: [],
         thirdFloorRooms: 0,
         thirdRoom: [],
         fourthFloorNumRooms: 0,
         fourthRoom: []
    }
    },
    {
      id: 39,
      title:  "Gym Building",
      description: "This is the Gym Building",
      textInfo: 'Gym Building'   ,
      uri: 8 ,
      latitude: 9.353475 ,
      longitude: 122.837080 ,
      latitudeText: 9.35349 ,
      longitudeText: 122.837080 ,
      buildingData: {
         numberOfFloors: 1,
         numberOfRooms: 0,
         groundFloorNumRooms:0,
         groundRoom: [] ,
         firstFloorNumRooms: 0,
         firstRoom: [],
         secondFloorNumRooms: 0,
         secondRoom: [],
         thirdFloorRooms: 0,
         thirdRoom: [],
         fourthFloorNumRooms: 0,
         fourthRoom: []
    }
    },
    {
      id: 40,
      title:  "Classroom Building 4",
      description: "This is the Class Room Building",
      textInfo: 'Classroom Building 4'   ,
      uri: 28 ,
      latitude:  9.352925  ,
      longitude:  122.838434 ,
      latitudeText:  9.352945  ,
      longitudeText:  122.838434  ,
      buildingData: {
         numberOfFloors: 1,
         numberOfRooms: 2,
         groundFloorNumRooms:2,
         groundRoom: ['Room1', 'Room2'] ,
         firstFloorNumRooms: 0,
         firstRoom: [],
         secondFloorNumRooms: 0,
         secondRoom: [],
         thirdFloorRooms: 0,
         thirdRoom: [],
         fourthFloorNumRooms: 0,
         fourthRoom: []
    }
    },
    {
      id: 40,
      title:  "Campus Dorm",
      description: "This is the Campus Dorm",
      textInfo: 'Campus Dorm'   ,
      uri: 28 ,
      latitude:  9.354707 ,
      longitude:  122.837431   ,
      latitudeText:  9.354707  ,
      longitudeText:  122.837431  ,
      buildingData: {
         numberOfFloors: 1,
         numberOfRooms: 2,
         groundFloorNumRooms:2,
         groundRoom: ['Room1', 'Room2'] ,
         firstFloorNumRooms: 0,
         firstRoom: [],
         secondFloorNumRooms: 0,
         secondRoom: [],
         thirdFloorRooms: 0,
         thirdRoom: [],
         fourthFloorNumRooms: 0,
         fourthRoom: []
    }
    },
    {
      id: 43,
      title:  "Dummy Test",
      description: "This is Dummy Building",
      textInfo: 'Campus Building'   ,
      uri: 28 ,
      latitude:  9.352879, 
      longitude: 122.837197 ,
      latitudeText:  9.352879,
      longitudeText: 122.837197 ,
      buildingData: {
         numberOfFloors: 1,
         numberOfRooms: 2,
         groundFloorNumRooms:2,
         groundRoom: ['Room1', 'Room2'] ,
         firstFloorNumRooms: 0,
         firstRoom: [],
         secondFloorNumRooms: 0,
         secondRoom: [],
         thirdFloorRooms: 0,
         thirdRoom: [],
         fourthFloorNumRooms: 0,
         fourthRoom: []
    }
    },
     ]
  },
  reducers: {
    addBuilding: (state,{payload}) => {
         state.buildingData = state.buildingData.concat(payload.data)
         console.log(payload.data)
         console.log('working')
    },
    removeBuilding: (state) => {
        state.buildingData.pop()
    },
    editBuilding: (state,{payload}) =>{
      state.defBuildingInfo = payload.data
      console.log(payload.data)
    },
  }
})

export const {
   addBuilding,
   removeBuilding,
   editBuilding
} = mongoDBSlice.actions

export default mongoDBSlice.reducer